// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using capstone_backend;

namespace capstone_backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191014174834_StructuredNotesForOneToMany")]
    partial class StructuredNotesForOneToMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("capstone_api.Models.Assign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<int>("PatientId");

                    b.Property<bool>("Read");

                    b.Property<string>("Resources");

                    b.Property<string>("Task");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("capstone_api.Models.Notes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Description");

                    b.Property<int>("PatientId");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("capstone_api.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Diagnoses");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Schedule");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("capstone_api.Models.PatientEmergencyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Description");

                    b.Property<int>("PatientId");

                    b.Property<bool>("Read");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientEmergencyLogs");
                });

            modelBuilder.Entity("capstone_api.Models.PatientLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Description");

                    b.Property<string>("Emotions");

                    b.Property<int>("PatientId");

                    b.Property<bool>("Read");

                    b.Property<string>("Title");

                    b.Property<string>("Triggers");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientLogs");
                });

            modelBuilder.Entity("capstone_api.Models.Assign", b =>
                {
                    b.HasOne("capstone_api.Models.Patient", "Patient")
                        .WithMany("Assignments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("capstone_api.Models.Notes", b =>
                {
                    b.HasOne("capstone_api.Models.Patient", "Patient")
                        .WithMany("Note")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("capstone_api.Models.PatientEmergencyLog", b =>
                {
                    b.HasOne("capstone_api.Models.Patient", "Patient")
                        .WithMany("PatientEmergencyLogs")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("capstone_api.Models.PatientLog", b =>
                {
                    b.HasOne("capstone_api.Models.Patient", "Patient")
                        .WithMany("PatientLogs")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
